name: build
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
          pip-install: build
      - run: python3 -m build --sdist --outdir wheelhouse
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          name: ${{ github.job }}
          path: wheelhouse/*
          if-no-files-found: error

  bdist:
    strategy:
      matrix:
        include:
          - variant: manylinux-x86-64
            runner: ubuntu-26.04
            archs: 'x86_64'
            build: '*manylinux*'
          - variant: musllinux-x86-64
            runner: ubuntu-26.04
            archs: 'x86_64'
            build: '*musllinux*'
          - variant: manylinux-aarch64
            runner: ubuntu-26.04-arm
            archs: 'aarch64'
            build: '*manylinux*'
          - variant: musllinux-aarch64
            runner: ubuntu-26.04-arm
            archs: 'aarch64'
            build: '*musllinux*'
          - variant: macosx-arm64
            runner: macos-26
            archs: 'arm64'
          - variant: macosx-x86-64
            runner: macos-26-intel
            archs: 'x86_64'
    name: ${{ matrix.variant }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'  # cibuildwheel needs a recent Python version
          cache: 'pip'
          pip-install: cibuildwheel~=4.2.0
      - run: python3 -m cibuildwheel
        env:
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_BUILD: ${{ matrix.build }}
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ github.job }}-${{ matrix.variant }}
          path: wheelhouse/*
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [sdist, bdist]
    environment: release
    permissions:
      contents: write  # github release api
      id-token: write  # pypi oidc
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheelhouse/
          merge-multiple: true
      - run: |
          gh release create \
            --repo "${{ github.repository }}" --draft --generate-notes \
            "$GITHUB_REF_NAME" wheelhouse/*
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
        with:
          packages-dir: wheelhouse/
