name: typecheck
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'pip'
          pip-install: -r requirements.txt
      - run: pyright
        env:
          PYRIGHT_PYTHON_PYLANCE_VERSION: latest-release
